"""
Mock LLM — 不依赖任何外部 API，用于测试与本地开发。

行为：
- 按 prompt 长度与关键词生成确定性响应
- 模拟 token 计数与延迟（可通过 latency_ms 参数控制）
- 完全可离线运行
"""

from __future__ import annotations

import hashlib
import time
from typing import Any, ClassVar, Dict, List, Optional, Sequence, Tuple

from .base import LLMClient, LLMResponse


class MockClient(LLMClient):
    """确定性的本地 mock。基于 prompt 的 hash 生成伪响应。"""

    provider = "mock"
    _MOCK_PATTERNS: ClassVar[List[Tuple[Tuple[str, ...], str]]] = [
        (("优先级", "priority", "排序"), "[mock] 建议优先级: 1.紧急任务 2.重要任务 3.常规任务"),
        (("拆解", "拆成", "分解", "步骤", "decompose"), "[mock] 步骤拆解: step1 -> step2 -> step3"),
        (("总结", "摘要", "summary"), "[mock] 摘要: 核心要点 A、B、C"),
        (("代码", "code", "script"), "[mock] ```python\n# generated by mock\npass\n```"),
    ]

    def __init__(self, model: str = "mock-v1", latency_ms: float = 10.0) -> None:
        self.model = model
        self._latency_ms = latency_ms

    # ------------------------------------------------------------ public API
    def complete(
        self,
        prompt: str,
        *,
        max_tokens: int = 1024,
        temperature: float = 0.7,
        system: Optional[str] = None,
        **kwargs: Any,
    ) -> LLMResponse:
        start = time.time()
        time.sleep(self._latency_ms / 1000)
        content = self._fake_response(prompt, system)
        elapsed = (time.time() - start) * 1000
        prompt_tokens = self._rough_token_count((system or "") + prompt)
        completion_tokens = self._rough_token_count(content)
        return LLMResponse(
            content=content,
            provider=self.provider,
            model=self.model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
            latency_ms=elapsed,
            raw={"mock": True, "seed": self._seed(prompt)},
        )

    def chat(
        self,
        messages: List[Dict[str, str]],
        *,
        max_tokens: int = 1024,
        temperature: float = 0.7,
        **kwargs: Any,
    ) -> LLMResponse:
        user_last = next(
            (m["content"] for m in reversed(messages) if m.get("role") == "user"), ""
        )
        system = next(
            (m["content"] for m in messages if m.get("role") == "system"), None
        )
        return self.complete(
            user_last, max_tokens=max_tokens, temperature=temperature, system=system
        )

    @classmethod
    def register_pattern(cls, keywords: Sequence[str], response: str) -> None:
        """Register a deterministic mock response pattern for tests or demos."""

        normalized = tuple(keyword.lower() for keyword in keywords if keyword)
        if not normalized:
            raise ValueError("keywords must contain at least one non-empty item")
        cls._MOCK_PATTERNS.append((normalized, response))

    # ----------------------------------------------------------- internals
    @staticmethod
    def _seed(prompt: str) -> str:
        return hashlib.md5(prompt.encode("utf-8")).hexdigest()[:8]

    @staticmethod
    def _rough_token_count(text: str) -> int:
        # 粗略近似：中文 1 字 ≈ 1 token，英文 4 字符 ≈ 1 token
        if not text:
            return 0
        cjk = sum(1 for ch in text if "\u4e00" <= ch <= "\u9fff")
        other = len(text) - cjk
        return cjk + max(other // 4, 1 if other else 0)

    def _fake_response(self, prompt: str, system: Optional[str]) -> str:
        # 关键词触发的伪响应，便于 skill 开发时断言行为；组合场景会合并多个命中模板。
        p = prompt.lower()
        matches = [
            response
            for keywords, response in self._MOCK_PATTERNS
            if any(keyword in p for keyword in keywords)
        ]
        if matches:
            return "\n".join(dict.fromkeys(matches))
        return f"[mock-{self._seed(prompt)}] {prompt[:50]}"
